package com.oreal.escript.parser.logging;

public enum LogEntryCode {
    SYNTAX_LOG,
    SOURCE_FILE_DOES_NOT_EXIST,
    SOURCE_FILE_NOT_READABLE,
    UNKNOWN_EXPRESSION,
    UNKNOWN_TYPE_REFERENCE,
    NO_TYPE_INFORMATION,
    VALUE_HAS_NO_TYPE,
    NO_SUCH_SYMBOL,
    SYMBOL_ALREADY_IN_SCOPE,
    TYPE_MISMATCH,
    CAST_OPERAND_HAS_NO_ADDRESS,
    EXPRESSION_IS_NOT_CONST,
}
