package org.estaos.pin.core.parser.logging;

public enum LogEntryCode {
    SYNTAX_LOG,
    SOURCE_FILE_DOES_NOT_EXIST,
    SOURCE_FILE_NOT_READABLE,
    UNKNOWN_EXPRESSION,
    UNKNOWN_TYPE_REFERENCE,
    NO_TYPE_INFORMATION,
    VALUE_HAS_NO_TYPE,
    NO_SUCH_SYMBOL,
    SYMBOL_ALREADY_IN_SCOPE,
    TYPE_MISMATCH,
    CAST_OPERAND_HAS_NO_ADDRESS,
    EXPRESSION_IS_NOT_CONST,
    EXPRESSION_IS_NOT_BOOLEAN,
    EXPRESSION_IS_NOT_NUMBER,
    RETURNING_FROM_VOID_CONTEXT,
    EXPRESSION_IS_NOT_CALLABLE,
    NOT_ENOUGH_ARGUMENTS_TO_FUNCTION,
    TOO_MANY_ARGUMENTS_TO_FUNCTIONS
}
