name: Regression Tests

on: pull_request

jobs:
  build:
    runs-on: windows-latest
    name: 'Pr Check'
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '22'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run regression
      working-directory: ./src/regression
      run: ./regression.sh

    - name: Test and install cli
      working-directory: ./src/cli
      run: mvn clean install
